name: Build & Test

on:
    push:
        branches:
            - develop
    pull_request:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
        
            - name: Build project
              run: make
              
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Run tests
              run: make test